Limit connections to 200 http and 100 https each to prevent DoS
ubports/ubuntu-push pull request #26
Opened 2020-11-20 23:57 UTC by Flohack74

From the running server deployment:
When the server is down Telegram will enqueue messages to be sent and then flood us with 1000s of simlutaneous connections. We are not AWS, so limit it to a sane level.

2020-11-21 00:50 UTC, mariogrip commented
humm, cant we bump it up more?

2020-11-21 18:27 UTC, Flohack74 commented
Sure gimme an idea what you would like. I think probably we can go for 10x those numbers easily. It was done ver restricted during the first and only DoS from Telegram servers in 2018 I think ;)

2020-11-23 18:27 UTC, dobey approved these changes
You also need to add `golang-golang-x-net-dev` to the `Build-Depends` list in the `debian/control` file.

2020-11-23 18:33 UTC, dobey requested changes
See previous comment.

2020-11-23 20:18 UTC, mariogrip approved these changes
LGTM :+1:

2020-11-23 20:18 UTC, merged